1. What is a Python library? Why do we use Python libraries?

Ans :  A Python library is a collection of pre-written code that provides functionality for a 
       specific task or set of tasks, which can be easily imported and used in Python programs.
       Python libraries are essentially modules or packages that contain functions, classes, and 
       methods to perform various operations, such as data manipulation, visualization, machine learning.
     
     Use of Python libraries:
     
     1.Code Reusability: Libraries provide reusable code, saving time and effort needed to write code from scratch. 
     Developers can leverage existing libraries to perform common tasks.

    2.Simplification: Libraries abstract complex operations and provide simple interfaces for developers. For example, 
     using libraries like NumPy or Pandas allows for handling complex mathematical operations and data manipulation with 
     simpler code.

    3.Efficiency: Libraries are often optimized for performance. They contain efficient algorithms that can handle tasks 
     faster than custom-written code.




2. What is the difference between Numpy array and List?


1.) Data Structure:

   NumPy Array: NumPy arrays are homogeneous, meaning all elements in the array must be of the same 
   data type (e.g., all integers, all floats).
   
   Python List: Python lists are heterogeneous and can contain elements of different data types 
   (e.g., integers, floats, strings, objects).
   
2.)Size:

   NumPy Array: NumPy arrays have a fixed size. Once an array is created, its size cannot be changed directly. To resize 
   or change the size of an array, you need to create a new array.
   
   Python List: Python lists are dynamic in size. You can easily add, remove, or modify elements after the list is created.
   
3.)Performance:

   NumPy Array: NumPy arrays are faster and more efficient for numerical computations because they are implemented in C 
   and optimized for such tasks.
   
   Python List: Python lists are slower because they are general-purpose data structures and involve more overhead.
   
4.)Memory Efficiency:

   NumPy Array: NumPy arrays are more memory-efficient because they store elements of the same data type contiguously,
   which optimizes memory usage.
   
   Python List: Python lists are less memory-efficient as they store references to objects rather than the actual objects
   themselves, which results in more memory overhead.
   
5.)Operations:

   NumPy Array: NumPy arrays support vectorized operations, meaning you can perform element-wise operations directly without 
   the need for explicit loops. This makes them highly efficient for mathematical computations.
   
   Python List: Python lists do not support vectorized operations, and typically require explicit loops to perform element-wise
   operations, which can be slower and less concise.

In [ ]:
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np
a = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print('Shape',a.shape)
print('Size',a.size)
print('Dimension' , a.ndim)

Shape (3, 4)
Size 12
Dimension 2


In [ ]:
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
import numpy as np
b =np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(b[0])


[1 2 3 4]


In [ ]:
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

c = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(c[2][3])


12


In [ ]:
6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np

d = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(d[::2,::2])



[[ 1  3]
 [ 9 11]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [19]:
import numpy as np

e = np.random.rand(3,3)
e

array([[0.80040482, 0.27887913, 0.88834502],
       [0.20943417, 0.72938241, 0.09014623],
       [0.88796155, 0.47446028, 0.69368372]])

8. Describe the difference between np.random.rand and np.random.randn?

 np.random.rand()
 Distribution: Uniform distribution over [0, 1).

    Usage: Generates random numbers that are uniformly distributed between 0 and 1.

    Syntax: np.random.rand(d0, d1, ..., dn)

    d0, d1, ..., dn: Dimensions of the output array.

In [20]:
import numpy as np
f = np.random.rand(2,2)
f

array([[0.52595391, 0.17373951],
       [0.06544048, 0.8960783 ]])

 np.random.randn()

 Distribution: Standard normal (Gaussian) distribution with mean 0 and standard deviation 1.
 
     Usage: Generates random numbers that are normally distributed.

    Syntax: np.random.randn(d0, d1, ..., dn)

     d0, d1, ..., dn: Dimensions of the output array.

In [21]:
import numpy as np

g = np.random.randn(3,3)
g

array([[-1.95133993,  0.85996057,  0.17392889],
       [-0.11512157, -1.10715202, -1.3803259 ],
       [-1.05221639,  1.3239394 ,  1.14018282]])

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [23]:
import numpy as np

h = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(np.expand_dims(h,axis=0))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [24]:
print(np.expand_dims(h,axis=1))

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [26]:
import numpy as np

i = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(np.transpose(i))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python

1.Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [29]:
import numpy as np
matrixA = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrixB= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

1.Index wise multiplication

In [33]:
im = np.multiply(matrixA,matrixB)
im

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

2. Matrix multiplication

In [35]:
matrixC = np.transpose(matrixB)
mm = np.dot(matrixA,matrixC)
mm

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

3. Add both the matrics

In [36]:
am = np.add(matrixA,matrixB)
am

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

4. Subtract matrix B from A

In [38]:
sm = np.subtract(matrixA,matrixB)
sm

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

5. Divide Matrix B by A

In [39]:
dm = np.divide(matrixB,matrixA)
dm

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
np.ndarray.byteswap(). This method changes the byte order of each element in the array, 
which can be useful for converting between little-endian and big-endian formats.

In [41]:
import numpy as np
a1 = np.array([1,3,6],dtype='>i2')
print('Printing the original array')
print(a1)
b1 = a1.byteswap()
print(b1)

Printing the original array
[1 3 6]
[ 256  768 1536]


13.What is the significance of the np.linalg.inv function?

The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. In linear algebra, the inverse of a matrix 
𝐴.A is another matrix 𝐴−1.A−1 such that when multiplied together, they yield the identity matrix 
𝐼
I: 𝐴 × 𝐴−1 = 𝐼 

Significance : 
   1.) Solving Linear Systems: The inverse of a matrix is useful for solving linear systems of equations. For example, if you have a system of 
    linear equations represented as 𝐴𝑥 = 𝑏
          Ax=b, where 𝐴
         A is a square matrix, 
        x is the vector of unknowns, and 
        b is a known vector, the solution can be found by:

          𝑥 =𝐴−1𝑏
2.)Matrix Transformations: In computer graphics, control theory, and various engineering applications, 
       matrix inverses are used to reverse transformations applied to objects or systems.




14. What does the np.reshape function do, and how is it used?

In [ ]:
The np.reshape() function in NumPy is used to change the shape of an array without altering its data. 
This function returns a new array with the specified shape, which must have the same number of elements as the original array.

In [42]:
import numpy as np
a3 = np.arange(12)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
b3 = np.reshape(a3,(3,4))

In [44]:
b3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

15. What is broadcasting in Numpy?

Broadcasting in NumPy is a technique that allows operations on arrays of different shapes to be performed 
together in a way that mimics having arrays of the same shape. This concept is fundamental for efficiently 
handling operations on arrays of varying dimensions and sizes.

In [45]:
import numpy as np
a4 = np.array([1,2,3,4])
scalar = 2
print(a4 + 2)

[3 4 5 6]
